<style>
    #free-domains-list {	-webkit-column-count: 6;
	-moz-column-count: 6;
	column-count: 6;

	-webkit-column-gap: 10px;
	-moz-column-gap: 10px;
	column-gap: 10px;}
</style>
<h3>Free Domains List</h3>
This list is downloaded from SpamAssassin - http://svn.apache.org/repos/asf/spamassassin/trunk/rules/20_freemail_domains.cf<br />
If you wish to remove some of these from blacklist, you can either add them to "Whitelist" or disable "Free Domains" check in Settings page.
<ul id="free-domains-list">
    <?php foreach ($domains as $domain): ?>
    <li><?php echo $domain->domain; ?></li>
    <?php endforeach; ?>
</ul>