<p class="clear">
<h3>Blacklisting tester</h3>
<?php if (isset($result)): ?>
<div class="updated">
The result for this domain (<?php echo strip_tags($domain); ?>) is: <strong><?php echo $result===true?'<font color="green">VALID</font>':'<font color="red">INVALID</font>'; ?></strong><br />
<?php echo $reason; ?></div>
<?php endif; ?>
Type a domain and check what is the result for it
<form method="post">
    <input type="text" name="domain" placeholder="domain.name.com" style="text-transform:lowercase" value="<?php if (!empty($domain)) echo esc_attr($domain); ?>"/><input type="submit" class="button" value="Check" />
</form>
</p>