<script>
    function editDomain(id) {
        var row = jQuery('#domain-row-'+id);
        var domainContainer = row.find('.domainText');
        if (domainContainer.find('input').length>0) return false;
        var input = jQuery('<input />').attr('type', 'text').attr('name', 'domain').css('text-transform', 'lowercase');
        var inputValue = domainContainer.text();
        var submit = jQuery('<input />').attr('type', 'submit').attr('value', 'Apply');
        domainContainer.empty().append(input.val(inputValue)).append(submit);
        
    }
    function deleteDomain(id) {
        var domainContainer = jQuery('#domain-row-'+id+' .domainText');
        var domainName = '';
        if (domainContainer.find('input').length>0)
            domainName = domainContainer.find('input[name=domain]').val();
        else
            domainName = domainContainer.text();
        if (confirm('Are you sure you want to delete domain: '+domainName+'?'))
            jQuery('#domain-row-'+id+' .deleteForm').submit();
    }
</script>
<h3>User Whitelist</h3>
<?php if (!empty($message)): ?>
<div class="updated below-h2"><p><?php echo $message; ?></p></div>
<?php endif; ?>
You can use full domain names (e.g. "gmail.com") or wildcards (e.g. "*mail.com").
<form method="post"><input type="hidden" name="cmeb_action" value="add" /><strong>Add new domain: </strong><input type="text"  style="text-transform:lowercase" name="domain" placeholder="domain.name.com" /><input type="submit" value="Add" /></form><br />
<table class="wp-list-table widefat">
    <thead>
        <tr valign="top">
            <th scope="col">Domain name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        if (!empty($domains)):
        foreach ($domains as $domain): ?>
            <tr id="domain-row-<?php echo $domain->id; ?>"><td><form method="post"><input type="hidden" name="cmeb_action" value="edit" /><input type="hidden" name="domain_id" value="<?php echo $domain->id; ?>" /><span class="domainText"><?php echo $domain->domain; ?></span></form></td>
                <td><a href="javascript:void(0)" onclick="editDomain(<?php echo $domain->id; ?>)">[Edit]</a> <form method="post" class="deleteForm" style="display:none"><input type="hidden" name="cmeb_action" value="delete" /><input type="hidden" name="domain_id" value="<?php echo $domain->id; ?>"/></form><a href="javascript:void(0)" onclick="deleteDomain(<?php echo $domain->id; ?>)">[Delete]</a></td>
            </tr>
        <?php endforeach; 
        else:
        ?>
            <tr><td colspan="2">There are no domains whitelisted</td></tr>
          <?php  
        endif;
?>
    </tbody>
</table>